Allow multiple selections for suggested packages

diff --git a/cli-aptiX b/cli-aptiX
--- a/cli-aptiX
+++ b/cli-aptiX
@@ -533,7 +533,7 @@ do_search() {
 
                 [ -n "$good" ] && break
 
-                warn "No valid number were given.  Please try again"
+                warn "No valid numbers were given.  Please try again"
             done
 
             case $action in
@@ -1678,56 +1678,69 @@ do_suggested() {
         while true; do
             [ "$skip" ] && break
             questn "Press %s to skip picking a package" "<$enter>"
-            questn "Or enter the number of the package you want to mark or install"
+            questn "Or enter the number(s) of the package(s) you want to mark or install"
+            questn "Use %s to indicate a range of numbers" "$(bqq -)"
             questn "Use %s to go to main menu, %s to see the results again" "$(bqq q)<$enter>" "$(bqq r)<$enter>"
             quest "> "
 
-            local number
-            read number
+            local input=
+            read input
 
-            case $number in
-                   "")  action=skip; break ;;
+            case $input in
+                   "") break    ;;
                 [qQ]*) return   ;;
-                [rR]*) action=review ; break ;;
-                #[sS]*) action=search ; break ;;
-                [1-9]|[1-9][0-9]|[1-9][0-9][0-9]) ;;
-                            [1-9][0-9][0-9][0-9]) ;;
-                       [1-9][0-9][0-9][0-9][0-9]) ;;
-                  [1-9][0-9][0-9][0-9][0-9][0-9]) ;;
-                *) warn "Invalid input.  Please try again" ; continue ;;
+                [rR]*) action=continue ; break ;;
             esac
 
-            if [ $number -gt $pack_cnt ]; then
-                warn "That number was out of range, please try again"
+            # Test for chars other than space, digits and comma
+            if ! is_num_range "$input"; then
+                warn "Invalid input.  Please try again"
                 continue
             fi
 
-            break
+            local num= bad= good= good_cnt=0
+            for num in $(num_range "$input" 1 $pack_cnt); do
+                if [ $num -lt 0 -o $num -gt $pack_cnt ]; then
+                    bad=$bad${bad:+ }$num
+                else
+                    good=$good${good:+ }$num
+                    good_cnt=$((good_cnt + 1))
+                fi
+            done
+
+            if [ -n "$bad" ]; then
+                warn "The following number(s) were out of range: %s" "$bad"
+            fi
+
+            [ -n "$good" ] && break
+
+            warn "No valid numbers were given.  Please try again"
         done
 
         case $action in
-            review) continue ;;
+            continue) continue ;;
+               break) break    ;;
         esac
 
-        local full_package=
+        local full_package=  pack_list=
 
-        if [ "$number" ]; then
-            full_package=$(cat $SEARCH_FILE | my_nl | sed -n -r "s/^\s*$number\s+//p")
+        msg "Selected package(s)"
+        for num in $good; do
+            full_package=$(cat $SEARCH_FILE |  my_nl | sed -n -r "s/^\s*$num\s+//p")
             if [ -z "$full_package" ]; then
-                warn "Could not find package number %s" "$number"
-                break
+                warn "Could not find package number %s" "$num"
+                continue
             fi
-
-            msg "Selected package number %s" "$(bq $number)"
-            show_package "$full_package"
-        fi
+            show_package "$full_package" $num
+            pack_list=$pack_list${pack_list:+ }$(package_name "$full_package")
+        done
 
         local action=
         # LOOP: package info
         while true; do
 
             local menu=$(
-                mark_or_install_menu "" "$full_package"
+                multi_mark_or_install_menu $pack_list
                 mark_all_menu        $SEARCH_FILE
                 install_all_menu     $SEARCH_FILE
                 menu_printf suggest  $"See suggestions again"
@@ -1741,6 +1754,8 @@ do_suggested() {
                       mark)        mark_package "$full_package"            ;;
                     unmark)      unmark_package "$full_package"            ;;
                    install)     install_package "$full_package"            ;;
+                    *-mark)           mark_list "${ans%-mark}"             ;;
+                 *-install)        install_list "${ans%-install}"          ;;
                  uninstall)   uninstall_package "$full_package"            ;;
                   mark-all)       mark_all_file $SEARCH_FILE               ;;
                 unmark-all)     unmark_all_file $SEARCH_FILE               ;;
